project:
  type: website

website:
  title: "ARSRL DigiEpi Workshop"
  navbar:
    logo: /img/digi-epi transparent.png
    left: 
      - href: index.qmd
        text: Home
      - href: agenda.qmd
        text: Agenda
      - href: Resource Speakers.qmd
        text: Resource Speakers
      - href: bioinformatics.qmd
        text: Concept Overview
      - text: Module
        menu:
          - Unit 1- ARSRL SaTScan and Whole Genome Sequencing Enhanced Outbreak Investigation Protocol.qmd
          - Unit 2- Digital Epidemiology Tool- EPICOLLECT.qmd
          - Unit 3- Digital Epidemiology Tool- PATHOGENWATCH.qmd
          - Unit 4- Digital Epidemiology Tool- MICROREACT.qmd
      - text: Workshop Materials
        menu:
          - Pre-Test.qmd
          - Post-Test.qmd
          - Workshop Evaluation.qmd
      - href: FAQs.qmd 
        text: Got a question?


  page-footer: 
    left: "This work is licensed under a Creative Commons Attribution 4.0 International License. Reuse is encouraged with acknowledgement" 
    right: 
      - icon: twitter 
        href: https://twitter.com/TheCGPS


format:
  html:
    theme:
      light: [materia, theme-light.scss]
      dark: [materia, theme-dark.scss]
    anchor-sections: true

editor: visual

execute:
  freeze: auto
  
sidebar:
  contents: auto

link-external-newwindow: true
